language: node_js

env:
  - FORCE_COLOR=true

node_js:
  - 10.12
  - 12
  - node

jobs:
  include:
    - stage: test
      script:
        - npm ci
        - npm run test:ci

    - stage: release
      deploy:
        provider: script
        node_js: lts/*
        skip_cleanup: true
        script:
          - npx semantic-release

stages:
  - name: test
    if: type = pull_request
  - name: release
    if: branch = master AND type != pull_request
