language: node_js

env:
  global:
    - FORCE_COLOR=true
  matrix:
    - ESLINT=5
    - ESLINT=6

node_js:
  - 10.12
  - 12
  - 14

before_script:
  - 'if [ -n "${ESLINT-}" ]; then npm install --no-save "eslint@${ESLINT}" ; fi'

jobs:
  include:
    - stage: test
      node_js: 14
      env: ESLINT=6
      script:
        - npm run format:check
        - npm run lint -- --max-warnings 0
    - stage: release
      if: branch = master AND type != pull_request
      node_js: 14
      env: ESLINT=6
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
