language: node_js

env:
  - FORCE_COLOR=true

jobs:
  include:
    - stage: test
      if: type = pull_request
      node_js:
        - 10.12
        - 12
        - node
      script:
        - npm run test:ci

    - stage: release
      if: branch = master AND type != pull_request
      deploy:
        provider: script
        node_js: lts/*
        skip_cleanup: true
        script:
          - npx semantic-release

