name: CI

on:
  push:
    branches:
      # semantic-release valid branches
      - '+([0-9])?(.{+([0-9]),x}).x'
      - 'main'
      - 'next'
      - 'next-major'
      - 'beta'
      - 'alpha'
  pull_request:
    types: [opened, synchronize]

jobs:
  code_validation:
    name: Code Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint -- --max-warnings 0

      - name: Check format
        run: npm run format:check

  test:
    name: Tests (Node v${{ matrix.node }} - ESLint v${{ matrix.eslint }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.12, 10, 12.0, 12, 14, 15]
        eslint: [5, 6, 7]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Install specific ESLint
        run: npm install --no-save eslint@${{ matrix.eslint }}

      - name: Run tests
        run: npm run test:ci
